# Max distance at which trade will work (defaulted to 50)
maxDistance: 30

# If set to true players will be able to trade when they are in different dimensions
# Set it to 1 if you want that (This will also ignore any distance)
ignoreWorlds: False

# Sound can also be in lower case these inputs will be accepted
# entity_illusioner_hurt
# entity.illusioner.hurt
# entity illusioner hurt
# This sound will be for example when trading starts
EnablePositiveSounds: True
PositiveSound: 'ENTITY_EXPERIENCE_ORB_PICKUP'

# This sound is player for example when player is too far away from trading partner
EnableNegativeSounds: True
NegativeSound: 'BLOCK_NOTE_BLOCK_BASS'

# Logging output of trade deals use 'File' for output to file or 'Console'
LogTrades: True
LogType: 'Console'

# How much money booth players need to have to start trade (set to 0 to not use it) requires vault and economy plugin
TradeTax: 0

# How much money will be added removed by single click
MoneyBaseQuantity: 100.0


# GUI materials
# Accepted formats
# GRAY_STAINED_GLASS
# GRAY STAINED GLASS
# GRAY.STAINED.GLASS
# gray stained glass

BorderMaterial: 'GRAY_STAINED_GLASS_PANE'

NonConfirmMaterial: 'RED_CONCRETE'

ConfirmMaterial: 'LIME_CONCRETE'

NonFinalizeMaterial: 'WRITABLE_BOOK'

FinalizeMaterial: 'ENCHANTED_BOOK'

AddXPMaterial: 'EXPERIENCE_BOTTLE'

RemoveXPMaterial: 'EXPERIENCE_BOTTLE'

PartnerXPMaterial: 'EXPERIENCE_BOTTLE'

AddMoneyMaterial: 'GOLD_NUGGET'

RemoveMoneyMaterial: 'GOLD_NUGGET'

PartnerMoneyMaterial: 'GOLD_NUGGET'
