name: ProximityTrade
version: '1.1.4'
main: org.ptrade.proximityTrade.ProximityTrade
api-version: '1.21'
softdepend: [Vault]

commands:
  trade:
    usage: /<command> <player>
    description: Invite other player to trade
    permission: proximityTrade.trade
  cancelTrade:
    usage: /<command>
    description: Cancel you last trade offer
    permission: proximityTrade.cancel

  reload:
    usage: /<command>
    description: Reload Main Config
    permission: proximityTrade.reload



